"""create log_entry

Revision ID: 246f368660b8
Revises: fe5783aa12dc
Create Date: 2026-01-02 10:24:30.592224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246f368660b8'
down_revision: Union[str, Sequence[str], None] = 'fe5783aa12dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_files', sa.Column('stored_path', sa.String(length=1024), nullable=False))
    op.add_column('log_files', sa.Column('environment', sa.String(length=50), nullable=True))
    op.add_column('log_files', sa.Column('log_type', sa.String(length=50), nullable=True))
    op.add_column('log_files', sa.Column('total_lines', sa.Integer(), nullable=True))
    op.add_column('log_files', sa.Column('parsed_lines', sa.Integer(), nullable=True))
    op.add_column('log_files', sa.Column('failed_lines', sa.Integer(), nullable=True))
    op.add_column('log_files', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('log_files', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.alter_column('log_files', 'source',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('log_files', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_column('log_files', 'num_lines')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_files', sa.Column('num_lines', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('log_files', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('log_files', 'source',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('log_files', 'processed_at')
    op.drop_column('log_files', 'error')
    op.drop_column('log_files', 'failed_lines')
    op.drop_column('log_files', 'parsed_lines')
    op.drop_column('log_files', 'total_lines')
    op.drop_column('log_files', 'log_type')
    op.drop_column('log_files', 'environment')
    op.drop_column('log_files', 'stored_path')
    # ### end Alembic commands ###
