"""create log_files

Revision ID: fe5783aa12dc
Revises: fe8959ee0a0a
Create Date: 2026-01-02 10:23:59.896676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe5783aa12dc'
down_revision: Union[str, Sequence[str], None] = 'fe8959ee0a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entries', sa.Column('log_file_id', sa.Integer(), nullable=False))
    op.add_column('log_entries', sa.Column('line_number', sa.Integer(), nullable=False))
    op.add_column('log_entries', sa.Column('parse_status', sa.String(length=16), nullable=False))
    op.add_column('log_entries', sa.Column('parse_error', sa.Text(), nullable=True))
    op.add_column('log_entries', sa.Column('parse_confidence', sa.Float(), nullable=True))
    op.add_column('log_entries', sa.Column('parser_name', sa.String(length=64), nullable=True))
    op.add_column('log_entries', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('log_entries', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('log_entries', 'level',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('log_entries', 'service',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('log_entries', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_log_entries_file_id'), table_name='log_entries')
    op.create_index(op.f('ix_log_entries_log_file_id'), 'log_entries', ['log_file_id'], unique=False)
    op.create_index(op.f('ix_log_entries_parse_status'), 'log_entries', ['parse_status'], unique=False)
    op.create_unique_constraint('uq_log_entries_file_line', 'log_entries', ['log_file_id', 'line_number'])
    op.drop_constraint(op.f('log_entries_file_id_fkey'), 'log_entries', type_='foreignkey')
    op.create_foreign_key(None, 'log_entries', 'log_files', ['log_file_id'], ['id'], ondelete='CASCADE')
    op.drop_column('log_entries', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entries', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'log_entries', type_='foreignkey')
    op.create_foreign_key(op.f('log_entries_file_id_fkey'), 'log_entries', 'log_files', ['file_id'], ['id'])
    op.drop_constraint('uq_log_entries_file_line', 'log_entries', type_='unique')
    op.drop_index(op.f('ix_log_entries_parse_status'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_log_file_id'), table_name='log_entries')
    op.create_index(op.f('ix_log_entries_file_id'), 'log_entries', ['file_id'], unique=False)
    op.alter_column('log_entries', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('log_entries', 'service',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('log_entries', 'level',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('log_entries', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('log_entries', 'created_at')
    op.drop_column('log_entries', 'parser_name')
    op.drop_column('log_entries', 'parse_confidence')
    op.drop_column('log_entries', 'parse_error')
    op.drop_column('log_entries', 'parse_status')
    op.drop_column('log_entries', 'line_number')
    op.drop_column('log_entries', 'log_file_id')
    # ### end Alembic commands ###
