"""initial schema

Revision ID: fe8959ee0a0a
Revises: 
Create Date: 2025-12-31 09:35:38.173360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8959ee0a0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('num_lines', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_files_id'), 'log_files', ['id'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['log_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_entries_ts_level_service', 'log_entries', ['timestamp', 'level', 'service'], unique=False)
    op.create_index(op.f('ix_log_entries_file_id'), 'log_entries', ['file_id'], unique=False)
    op.create_index(op.f('ix_log_entries_id'), 'log_entries', ['id'], unique=False)
    op.create_index(op.f('ix_log_entries_level'), 'log_entries', ['level'], unique=False)
    op.create_index(op.f('ix_log_entries_service'), 'log_entries', ['service'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_service'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_level'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_file_id'), table_name='log_entries')
    op.drop_index('idx_log_entries_ts_level_service', table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_log_files_id'), table_name='log_files')
    op.drop_table('log_files')
    # ### end Alembic commands ###
